name: metavosgiens

services:
  nextjs:
    build:
      context: .
      target: runner
      args:
        NEXT_PUBLIC_GA_ID: ${NEXT_PUBLIC_GA_ID:-G-8FQSPEB2ZC}
    container_name: metavosgiens_nextjs
    restart: unless-stopped
    env_file:
      - .env.prod.local
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true
